### ISSUE TITLE
Bytes written...

### ISSUE THREAD

**Issue by cyboy22** [boostorg/redis#108]
Hi - Is there a way to disable the "Bytes Written..." message to std::cout (or std::err) as I cannot see anything obvious in the "config.hpp" header file.

**Comment by mzimbres** [comment]
You can decrease the log level to, say, `crit`. For example

```cpp
conn->async_run(cfg, {boost::redis::logger::level::crit}, net::consign(net::detached, conn));
```

**Comment by cyboy22** [comment]
Thanks!
