### ISSUE TITLE
Integrate Boost.Redis in the Boost build system

### ISSUE THREAD

**Issue by mzimbres** [boostorg/redis#118]
The time has come. Changes from the boost review have been implemented, users were gained, tests and new features look stable etc. It is time to integrate with Boost and reach more users with official Boost releases.

**Comment by jbrezina** [comment]
Any plans on this please?

**Comment by mzimbres** [comment]
Yes, this is top priority. Someone (@anarthal) offered some help so we might be able to get into 1.84. I have been sick for some weeks and could not dedicate much time here.
