### ISSUE TITLE
Health check not restart after connection lost

### ISSUE THREAD

**Issue by ysc3839** [boostorg/redis#122]
In cpp20_subscriber, the health checker periodically logs `Bytes written: 32`. But after `CLIENT kill`, the log disappear.
Personally guess it's because `checker_has_exited_` is not reset to false:
https://github.com/boostorg/redis/blob/46525371b9247a1ec208a6157880ec77f5ddadc4/include/boost/redis/detail/health_checker.hpp#L39-L42

**Comment by mzimbres** [comment]
Thanks for reporting, My time is a bit constrained these days. I will have a look at it in the next weekend.
