### ISSUE TITLE
Automatically `SELECT` database after `HELLO`?

### ISSUE THREAD

**Issue by ysc3839** [boostorg/redis#123]
Currently there's not an `on_connect` callback, so it would be helpful to execute `SELECT` automatically after `HELLO`.

**Comment by criatura2** [comment]
Good point. It would be even better if the `HELLO` command would allow `SELECT`ing automatically since this is the first command to be executed.

**Comment by mzimbres** [comment]
This looks like an important addition, I will think more about where exactly it should be implemented. We can put it in the connection `config` so that if set it gets sent with `HELLO`.
