### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by yudaichen** [boostorg/redis#139]
Will Redis connection pooling be supported in the future?

**Comment by mzimbres** [comment]
Boost.Redis is async and implements command multiplexing, that means it does not need a connection pool. In fact, a connection pool may slow down you application since it prevents bigger command pipelines.

**Comment by mzimbres** [comment]
Do you need any more info? Can we close this ticket?

**Comment by yudaichen** [comment]
Okay, thank you for the answer
