### ISSUE TITLE
[docs] Navigation panel improperly rendered

### ISSUE THREAD

**Issue by Lastique** [boostorg/redis#194]
https://www.boost.org/doc/libs/1_84_0/libs/redis/doc/html/index.html

The navigation panel seems to be overlapping the library title, and the search bar overlaps the panel.

![Screenshot_20240323_110356](https://github.com/boostorg/redis/assets/1589747/9e5f3dcf-080f-4643-bb42-b0fcdf4c9ef8)

Firefox 124.0.1, Kubuntu 22.04.

**Comment by Lastique** [comment]
The same issue is on the Reference page.

**Comment by mzimbres** [comment]
Hi, I am aware of this problem but still don't have a solution. It first appeared when Boost.Redis was integrated into boost and that boost header got automatically added to the docs. @anarthal has also investigated but AFAIR it was not trivial to fix.

**Comment by anarthal** [comment]
AFAIR it is a CSS problem on the Doxygen template you were using. It uses absolute positioning, assuming there is nothing on top of it. When the website adds the header, it breaks.

I thought I had fixed it though, but looks like it broke again. Probably the best way to handle this is preventing the website from including the header - let me investigate on whether this is possible and I'll come back to you.

**Comment by Lastique** [comment]
I just checked https://www.boost.org/doc/libs/master/libs/redis/doc/html/index.html and indeed it looks fixed. Was the fix made post-1.84 release? If so, you can close this and sorry for the noise.

**Comment by anarthal** [comment]
Looking at the commit history, yes, I fixed it after 1.84. This explains what we're seeing.
