### ISSUE TITLE
Missing release notes for Boost 1.87.0

### ISSUE THREAD

**Issue by bruno-viva** [boostorg/redis#223]
Hi,

It seems that the recent release doesn't include the change notes for the Redis lib?

https://www.boost.org/users/history/version_1_87_0.html

I checked the code and it does seem to include the recent changes made.

Thanks

**Comment by mzimbres** [comment]
Hi Bruno,

I keep my own release notes here: https://github.com/boostorg/redis?tab=readme-ov-file#changelog

I did not have the time to update the Boost release notes, will do it next time.

**Comment by bruno-viva** [comment]
Thanks!
