### ISSUE TITLE
memory_resource is still experimental in libc++

### ISSUE THREAD

**Issue by nejati-deriv** [boostorg/redis#38]
`libc++` doesn't have an `memory_resource` include file at this moment and we have to use `<experimental/memory_resource>`.
It is going to be fixed in clang-16 though [Release Note](https://libcxx.llvm.org/ReleaseNotes.html#what-s-new-in-libc-16-0-0).

**Comment by mzimbres** [comment]
I am wondering if Aedis should use `#include <boost/json/memory_resource.hpp>` instead of `std`. I have to sepup CI for `libc++`.

**Comment by mzimbres** [comment]
Memory resource has been removed https://github.com/boostorg/redis/pull/57.
