### ISSUE TITLE
Docs must explain the async_run rationale

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/redis#45]
The documentation should explain the rationale for this:
```
co_await ( conn->async_run() || conn->async_exec( req, adapt(resp) ) );
```

A "FAQ" section could be a good approach.

**Comment by mzimbres** [comment]
I am removing the emphasis on operator|| from the main doc. There will be only a brief mention that for certain cases this might be useful, here are the changes: https://github.com/boostorg/redis/tree/51-more-suggestions-for-documentation-improvements.

**Comment by mzimbres** [comment]
Fix: https://github.com/boostorg/redis/commit/d01a9acf3b5b8f6a942cc8339f2308e9b85889e5
