### ISSUE TITLE
We do not HANG

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/redis#48]
`async_receive` Javadoc should not use the word "hang". Consider this instead:

> When pushes arrive and there is no `async_receive` operation in progress, pushed data, requests, and responses will be paused until async_receive is called again

**Comment by mzimbres** [comment]
Fixed: https://github.com/boostorg/redis/commit/8b02268182fdf77d8fb16a5a3887b5926f37df06#diff-9de8f3a7aafe6aa5ccdd13d12ef3dca7626a5e8006b1d7cd16e6efa017765bb7R142
