### ISSUE TITLE
how do I build the docs?

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/redis#76]
I don't see instructions

**Comment by mzimbres** [comment]
Where do you expect the instructions? I am using cmake built-in Doxygen support with a preset, for example

```
cmake --preset dev
cmake --build --preset dev --target doc
```

Will generate the docs in 

`"DOXYGEN_OUTPUT_DIRECTORY": "${sourceDir}/build/dev/doc/"`

See CMakePreset.json.
